#!/bin/bash

#Time synchronization
echo "[Time]" > /etc/systemd/timesyncd.conf
echo "NTP=a.st1.ntp.br b.st1.ntp.br c.st1.ntp.br d.st1.ntp.br gps.ntp.br a.ntp.br b.ntp.br c.ntp.b" >> /etc/systemd/timesyncd.conf
timedatectl set-ntp true


chonosDDNSManager --conf -d `/usr/bin/hostname` -u "ddns_user" -t "ddns_token"

if [ -d /run/systemd/system ]; then
    systemctl daemon-reload
	systemctl restart	systemd-timesyncd
	systemctl restart	chonos-task.service
	systemctl restart	chonos-log.service
	systemctl restart	chonos-sysconfig.service
	systemctl restart	contextNetServer.service
	systemctl restart	ssh.service
	systemctl restart 	chonos-ddnsAutoUpdater.service
	systemctl start		choncloud-boot.service
fi
systemctl enable systemd-timesyncd
systemctl enable chonos-log.service
systemctl enable chonos-sysconfig.service
systemctl enable chonos-task.service
systemctl enable contextNetServer.service
systemctl enable ssh.service
systemctl enable chonos-ddnsAutoUpdater.service
systemctl enable choncloud-boot.service