#!/bin/bash

#Time synchronization
echo "[Time]" > /etc/systemd/timesyncd.conf
echo "NTP=a.st1.ntp.br b.st1.ntp.br c.st1.ntp.br d.st1.ntp.br gps.ntp.br a.ntp.br b.ntp.br c.ntp.b" >> /etc/systemd/timesyncd.conf
timedatectl set-ntp true
service systemd-timesyncd restart

#SSH Root Login
cat /etc/ssh/sshd_config | grep -v PermitRoot > /tmp/sshd_config
echo "PermitRootLogin yes" >> /tmp/sshd_config 
mv /tmp/sshd_config /etc/ssh/sshd_config
systemctl enable ssh

#Auto update every boot
cat /etc/rc.local | grep -v "exit 0" | grep -v "chonosDDNSManager" > /tmp/rc.local
echo "chonosDDNSManager --conf -d `/usr/bin/hostname`"
echo "chonosDDNSManager --update"
echo "exit 0" >> /tmp/rc.local
cat /tmp/rc.local > /etc/rc.local
chmod +x /etc/rc.local

systemctl daemon-reload
systemctl enable chonos-log.service
systemctl start  chonos-log.service
systemctl enable chonos-sysconfig.service
systemctl start  chonos-sysconfig.service
systemctl enable chonos-task.service
systemctl start  chonos-task.service
systemctl enable contextNetServer.service
systemctl start  contextNetServer.service